name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: | 
          echo "echo "wassup, bmore!"
          echo "hello, world"
          echo "hola, amigo!"
      - name: Print Goodbye
        run: echo "have a good one, bmore!"
